apiVersion: v1
kind: Service
metadata:
  name: ingress-api
spec:
  type: NodePort
  selector:
    app: ingress-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
