apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-api
  labels:
    app: ingress-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-api
  template:
    metadata:
      labels:
        app: ingress-api
    spec:
      containers:
        - name: ingress-api
          image: ingress:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: Kafka__Broker
              value: kafka:9092
            - name: Kafka__Topic
              value: sensor-data
            - name: Kafka__GroupId
              value: ingress-group
            - name: InfluxDbConfig__Url
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: INFLUXDB_URL
            - name: InfluxDbConfig__Org
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: DOCKER_INFLUXDB_INIT_ORG
            - name: InfluxDbConfig__Bucket
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: DOCKER_INFLUXDB_INIT_BUCKET
            - name: InfluxDbConfig__Token
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
