apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-api
  labels:
    app: ingress-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-api
  template:
    metadata:
      labels:
        app: ingress-api
    spec:
      containers:
        - name: ingress-api
          image: ingress:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: Kafka__Broker
              value: kafka:9092
            - name: Kafka__Topic
              value: sensor-data
            - name: Kafka__GroupId
              value: ingress-group
            - name: InfluxDbConfig__Url
              value: http://influxdb:8086
            - name: InfluxDbConfig__Token
              value: influxdb-token
            - name: InfluxDbConfig__Org
              value: myorg
            - name: InfluxDbConfig__Bucket
              value: ingress
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-api
spec:
  type: NodePort
  selector:
    app: ingress-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
