apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
  namespace: default
data:
  DOCKER_INFLUXDB_INIT_ORG: myorg
  DOCKER_INFLUXDB_INIT_BUCKET: ingress
  INFLUXDB_URL: http://influxdb:8086
