apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  labels:
    app: influxdb
  namespace: default
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: influxdb-token
  DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
  DOCKER_INFLUXDB_INIT_USERNAME: admin
